# NumPy

[NumPy](https://numpy.org) est une librairie en Python qui permet de manipuler des tableaux de plusieurs dimensions. Il possède des fonctions avancées dans le domaine de l'algèbre linéaire, de l'analyse statistique et de la transformation de données.

In [1]:
import numpy as np

# Créer des tableaux avec NumPy

Les tableaux sous NumPy peuvent être créés de plusieurs manières, nous allons voir certaines d'entre elles. La [documentation de NumPy](https://numpy.org/doc/stable/) explique en détail comment [créer des tableaux](https://numpy.org/doc/stable/reference/routines.array-creation.html).

In [2]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [4]:
np.random.random(5)

array([0.88221054, 0.97647112, 0.14121777, 0.11096297, 0.76982535])

In [5]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [7]:
np.random.random((2, 2))

array([[0.88707852, 0.66181208],
       [0.27745031, 0.22365533]])

In [8]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

# Operations de base sur les tableaux

In [13]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [11]:
a + 2

array([3., 3., 3., 3., 3.])

In [12]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [14]:
a + b

array([2., 3., 4., 5., 6.])

In [15]:
# Sélection des données dans un tableau 1D

b[1:4]

array([2, 3, 4])

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Inverser les colones

a[:, ::-1]

In [ ]:
# Inverser les lignes

a[::-1]

In [ ]:
# Sélectionner une partie des lignes et des colones

a[1:3, 1:3]

# Functions statistiques

In [ ]:
a = np.array([1, 2, 3, 4, 5])

# Mean (average)

np.mean(a)

In [ ]:
# Standard deviation

np.std(a)

In [ ]:
# Minimum value

np.min(a)

In [ ]:
# Index if maximum value

np.argmax(a)

# Algebre Linéaire

In [ ]:
a = 2 * np.ones(5)
b = np.array([1, 2, 3, 4, 5])

# Dot product of two vectors

a.dot(b)

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

In [ ]:
# Transpose of a matrix

a.T

In [ ]:
# Determinant of a matrix

np.linalg.det(a)

In [ ]:
# Inverse of a matrix

b = np.linalg.inv(a)
b

In [ ]:
a.dot(b)

# Visualisation des données

[Matplotlib](https://matplotlib.org) est une puissante librairie permettant de visualiser les données et facile à utliser. Elle peut être utilisée avec NumPy et Pandas.

In [ ]:
import math
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(0, 2*math.pi, 2*math.pi/50)
sin = np.sin(x)
cos = np.cos(x)

In [ ]:
plt.plot(x, sin, label='sin(x)', color='blue', linewidth=2.5)
plt.plot(x, cos, label='cos(x)', color='red', linewidth=0.5)
plt.ylabel('y')
plt.xlabel('x')
plt.legend(loc='upper right')
plt.show()

In [ ]:
plt.scatter(x, sin, label='sin(x)', color='green')
plt.ylabel('y')
plt.xlabel('x')
plt.legend(loc='upper right')
plt.show()

In [ ]:
x = np.arange(0, math.pi, math.pi/10)
plt.bar(x, np.sin(x), align='center', width=0.2)

In [ ]:
x = np.arange(0, math.pi, math.pi/10)
plt.barh(x, np.sin(x), align='center', height=0.2)

# Travailler avec des images

NumPy et Matplotlib permettent de travailler avec des images.

In [ ]:
from skimage import io

In [ ]:
h500 = io.imread('https://madhu.com/images/h500.gif')
plt.imshow(h500)

In [ ]:
h500.shape

In [ ]:
plt.imshow(h500[:, ::-1])

In [ ]:
plt.imshow(h500[::-1])

In [ ]:
plt.imshow(h500[100:200, 100:250])

# Transformer les données

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

In [ ]:
a.reshape(4, 1)

In [ ]:
a.reshape(1, 4)

In [ ]:
a.reshape(4, 1).shape

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

In [ ]:
a.shape

In [ ]:
a.reshape(3, 2)

In [ ]:
a = np.arange(0, 6)
a

In [ ]:
a.reshape(2, 3)